Fix image transforms options
supabase-community/storage-py pull request #149
Opened 2023-09-26 17:30 UTC by silentworks

## What kind of change does this PR introduce?

Bug fix to get image transforms working.

## What is the current behavior?

Currently image transforms aren't being passed over correctly as we are checking for "transform" in the options property while we only have the direct transform properties there.

## What is the new behavior?

Added the additional "transform" key to the dict hence allowing the transforms to work correctly.

## Additional context

Add any other context or screenshots.

2023-09-26 18:01 UTC, anand2312 requested changes

2023-09-26 19:45 UTC, silentworks commented on CHANGELOG.md
> +Bumps [pytest](https://github.com/pytest-dev/pytest) from 7.3.1 to 7.3.2.
I have no idea why `black` didn't like the changelog and decided to format it.

2023-09-26 19:47 UTC, silentworks commented on storage3/_sync/file_api.py
> +    def get_public_url(self, path: str, options: Options = {"transform": {}}) -> str:
I thought about URLOptions but thought the naming didn't make sense with the `download` method having that property too.

2023-09-26 19:47 UTC, silentworks commented on storage3/_sync/file_api.py
> +    def get_public_url(self, path: str, options: Options = {"transform": {}}) -> str:
Oh wait I re-read what you suggested, yeah that makes sense.

2023-09-27 21:48 UTC, silentworks commented on CHANGELOG.md
> +Bumps [pytest](https://github.com/pytest-dev/pytest) from 7.3.1 to 7.3.2.
It seems there was an issue with line endings hence why the pre-commit command changed this.
![Screenshot 2023-09-27 at 21-42-47 Rename options typehint · supabase-community_storage-py@4fc7d8d](https://github.com/supabase-community/storage-py/assets/79497/1d3d252c-0006-4e5c-a0eb-fcbe83e4b982)

2023-09-28 06:40 UTC, J0 approved these changes
LGTM, thanks for putting this together! Could you please update the reference spec  as well when a slot frees up?

2023-09-28 08:43 UTC, silentworks commented
Yeah I will update the reference docs for all these.

2023-09-28 08:43 UTC, merged

2023-09-28 10:40 UTC, anand2312 commented on storage3/_async/file_api.py
> +        query_string = f"?{query_string}"
A little confused by this diff - why are we manually constructing the query string instead of letting urllib.parse.urlencode do the work?